/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Logica.EnfermeroHospital;
import Logica.Hospital;
import Logica.MedicoHospital;
import Logica.MiLista;
import Logica.Principal;
import javax.swing.JOptionPane;



public class FormMedicoEnferm extends javax.swing.JPanel {

  private MiLista<EnfermeroHospital> listaEnfermeros = new MiLista<>();
  private MiLista<MedicoHospital>listaMedicos=new MiLista<>();
  private MiLista<Hospital> listaHospitales;

    public FormMedicoEnferm() {
        initComponents();
       Principal interfaz = new Principal(); 
        listaHospitales = interfaz.obtenerListaHospitales();
     
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputMatMedico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputEspMedico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        inputNacMedico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inputDniMedico = new javax.swing.JTextField();
        inputFecNacMedico = new javax.swing.JTextField();
        inputSexoMedico = new javax.swing.JTextField();
        inputNombreMedico = new javax.swing.JTextField();
        AgregarMedicoAlista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        crearMedConEnfemeros1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputTituloEnfermero = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        inputInstitucionEnfermero = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        inputNacEnfermero = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        inputDniEnfermero = new javax.swing.JTextField();
        inputFecNacEnfermero = new javax.swing.JTextField();
        inputSexoEnfermero = new javax.swing.JTextField();
        inputNombreEnfermero = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        crearEnfermeros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(700, 800));

        jLabel1.setText("Cargar medico");

        jLabel5.setText("Sexo:");

        jLabel11.setText("Matricula:");

        jLabel12.setText("DNI:");

        jLabel13.setText("Fecha de Nacimiento:");

        AgregarMedicoAlista.setBackground(new java.awt.Color(132, 255, 102));
        AgregarMedicoAlista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgregarMedicoAlista.setForeground(new java.awt.Color(255, 255, 255));
        AgregarMedicoAlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        AgregarMedicoAlista.setText("Agregar");
        AgregarMedicoAlista.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        AgregarMedicoAlista.setBorderPainted(false);
        AgregarMedicoAlista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarMedicoAlista.setDoubleBuffered(true);
        AgregarMedicoAlista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AgregarMedicoAlista.setIconTextGap(8);
        AgregarMedicoAlista.setPreferredSize(new java.awt.Dimension(10, 10));
        AgregarMedicoAlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMedicoAlistaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel22.setText("Deseas cargar todos los medicos al hospital seleccionado?");

        jLabel9.setText("Especialidad:");

        jLabel10.setText("Nacionalidad:");

        crearMedConEnfemeros1.setBackground(new java.awt.Color(132, 255, 102));
        crearMedConEnfemeros1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearMedConEnfemeros1.setForeground(new java.awt.Color(255, 255, 255));
        crearMedConEnfemeros1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        crearMedConEnfemeros1.setText("Agregar");
        crearMedConEnfemeros1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        crearMedConEnfemeros1.setBorderPainted(false);
        crearMedConEnfemeros1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearMedConEnfemeros1.setDoubleBuffered(true);
        crearMedConEnfemeros1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearMedConEnfemeros1.setIconTextGap(8);
        crearMedConEnfemeros1.setPreferredSize(new java.awt.Dimension(10, 10));
        crearMedConEnfemeros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMedConEnfemeros1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre completo:");

        jLabel2.setText("Cargar equipo de enfermeros");

        jLabel6.setText("Sexo:");

        labelTitulo.setText("Titulo:");

        jLabel25.setText("DNI:");

        jLabel26.setText("Fecha de Nacimiento:");

        inputSexoEnfermero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSexoEnfermeroActionPerformed(evt);
            }
        });

        jLabel27.setText("Institucion:");

        jLabel28.setText("Nacionalidad:");

        crearEnfermeros.setBackground(new java.awt.Color(132, 255, 102));
        crearEnfermeros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearEnfermeros.setForeground(new java.awt.Color(255, 255, 255));
        crearEnfermeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        crearEnfermeros.setText("Agregar");
        crearEnfermeros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        crearEnfermeros.setBorderPainted(false);
        crearEnfermeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearEnfermeros.setDoubleBuffered(true);
        crearEnfermeros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearEnfermeros.setIconTextGap(8);
        crearEnfermeros.setPreferredSize(new java.awt.Dimension(10, 10));
        crearEnfermeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEnfermerosActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre completo:");

        jLabel14.setText("Cargar hasta 5 enfermeros por medico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(inputNombreEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(inputSexoEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(inputFecNacEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(inputDniEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(inputNacEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(inputInstitucionEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(labelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(inputTituloEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(crearEnfermeros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel14)))
                .addGap(59, 59, 59)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputFecNacMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputNacMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputEspMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputMatMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(crearMedConEnfemeros1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel22))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(AgregarMedicoAlista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNombreEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSexoEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputFecNacEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDniEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNacEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputInstitucionEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTituloEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitulo))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crearEnfermeros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputFecNacMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(8, 8, 8)
                        .addComponent(inputDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNacMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputEspMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputMatMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(48, 48, 48)
                        .addComponent(crearMedConEnfemeros1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jLabel22)
                .addGap(4, 4, 4)
                .addComponent(AgregarMedicoAlista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMedicoAlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMedicoAlistaActionPerformed
        
      int obtenerUltimo = listaHospitales.getTamaño()-1;
      listaHospitales.obtener(obtenerUltimo).setMedicos(listaMedicos);
        
        listaMedicos= new MiLista();
        
     
    }//GEN-LAST:event_AgregarMedicoAlistaActionPerformed

    private void crearMedConEnfemeros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMedConEnfemeros1ActionPerformed
 String nombreMedico = inputNombreMedico.getText();
 String sexoMedico= inputNombreMedico.getText();
 String fecNacMedico= inputFecNacMedico.getText();
 String dniMedico= inputDniMedico.getText();
 String nacMedico=inputNacMedico.getText();
  String especialidad = inputEspMedico.getText();
 String matricula= inputMatMedico.getText();

 MedicoHospital  medicoHospital = new MedicoHospital();
 
medicoHospital.setNombre(nombreMedico);
medicoHospital.setSexo(sexoMedico);
medicoHospital.setDni(dniMedico);
medicoHospital.setFechaNacimiento(fecNacMedico);
medicoHospital.setNacionalidad(nacMedico);
medicoHospital.setEspecialidad(especialidad);
medicoHospital.setMatricula(matricula);
medicoHospital.setEnfermeros(listaEnfermeros);

listaMedicos.agregar(medicoHospital);

JOptionPane.showMessageDialog(null, "Medico con su grupo de enfermero se  ha guardado correctamente");


listaEnfermeros=new MiLista();

 inputNombreMedico.setText("");
inputSexoMedico.setText("");
inputFecNacMedico.setText("");
 inputDniMedico.setText("");
inputNacMedico.setText("");
inputEspMedico.setText("");
inputMatMedico.setText("");


    }//GEN-LAST:event_crearMedConEnfemeros1ActionPerformed

    private void crearEnfermerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEnfermerosActionPerformed
       String nombreEnfermero = inputNombreEnfermero.getText();
 String sexoEnfermero= inputSexoEnfermero.getText();
 String fecNacEnfermero= inputFecNacEnfermero.getText();
 String dniEnfermero= inputDniEnfermero.getText();
 String nacEnfermero=inputNacEnfermero.getText();
  String institucionEnfermero = inputInstitucionEnfermero.getText();
 String tituloEnfermero= inputTituloEnfermero.getText();
 

 
EnfermeroHospital enfermero = new EnfermeroHospital();
enfermero.setNombre(nombreEnfermero);
enfermero.setSexo(sexoEnfermero);
        enfermero.setFechaNacimiento(fecNacEnfermero);
        enfermero.setDni(dniEnfermero);
        enfermero.setNacionalidad(nacEnfermero);
        enfermero.setInstitucion(institucionEnfermero);
        enfermero.setTitulo(tituloEnfermero);
        
                
     listaEnfermeros.agregar(enfermero);
     JOptionPane.showMessageDialog(null, "Enfermero se ha guardado  correctamente");
     
     
     inputNombreEnfermero.setText("");
     inputSexoEnfermero.setText("");
     inputFecNacEnfermero.setText("");
     inputDniEnfermero.setText("");
     inputNacEnfermero.setText("");
     inputInstitucionEnfermero.setText("");
     inputTituloEnfermero.setText("");
     
    }//GEN-LAST:event_crearEnfermerosActionPerformed

    private void inputSexoEnfermeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSexoEnfermeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSexoEnfermeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMedicoAlista;
    private javax.swing.JButton crearEnfermeros;
    private javax.swing.JButton crearMedConEnfemeros1;
    private javax.swing.JTextField inputDniEnfermero;
    private javax.swing.JTextField inputDniMedico;
    private javax.swing.JTextField inputEspMedico;
    private javax.swing.JTextField inputFecNacEnfermero;
    private javax.swing.JTextField inputFecNacMedico;
    private javax.swing.JTextField inputInstitucionEnfermero;
    private javax.swing.JTextField inputMatMedico;
    private javax.swing.JTextField inputNacEnfermero;
    private javax.swing.JTextField inputNacMedico;
    private javax.swing.JTextField inputNombreEnfermero;
    private javax.swing.JTextField inputNombreMedico;
    private javax.swing.JTextField inputSexoEnfermero;
    private javax.swing.JTextField inputSexoMedico;
    private javax.swing.JTextField inputTituloEnfermero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
