/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Logica.Hospital;
import Logica.MiLista;
import Logica.Principal;
import Logica.Recepcionista;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FormRecepcionista extends javax.swing.JPanel {
  private MiLista<Hospital> listaHospitales;
  private MiLista <Recepcionista> listaRecepcionista = new MiLista<>();

    public FormRecepcionista() {
        initComponents();
          Principal interfaz = new Principal(); 
        listaHospitales = interfaz.obtenerListaHospitales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNacRecep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputDepRecep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputNombreRecep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputSexoRecep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputDniRecep = new javax.swing.JTextField();
        botonPrincipal1 = new javax.swing.JButton();
        agregarAlHospital = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        inputNacRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNacRecepActionPerformed(evt);
            }
        });

        jLabel8.setText("Nacionalidad:");

        inputDepRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDepRecepActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        jLabel4.setText("Departamento:");

        inputNombreRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreRecepActionPerformed(evt);
            }
        });

        jLabel5.setText("DNI:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel9.setText("Nombre completo:");

        inputSexoRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSexoRecepActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel1.setText("Carga personal recepcionista");

        inputDniRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDniRecepActionPerformed(evt);
            }
        });

        botonPrincipal1.setBackground(new java.awt.Color(132, 255, 102));
        botonPrincipal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonPrincipal1.setForeground(new java.awt.Color(255, 255, 255));
        botonPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        botonPrincipal1.setText("Agregar");
        botonPrincipal1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonPrincipal1.setBorderPainted(false);
        botonPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPrincipal1.setDoubleBuffered(true);
        botonPrincipal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPrincipal1.setIconTextGap(8);
        botonPrincipal1.setPreferredSize(new java.awt.Dimension(10, 10));
        botonPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrincipal1ActionPerformed(evt);
            }
        });

        agregarAlHospital.setBackground(new java.awt.Color(132, 255, 102));
        agregarAlHospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarAlHospital.setForeground(new java.awt.Color(255, 255, 255));
        agregarAlHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        agregarAlHospital.setText("Agregar al hospital");
        agregarAlHospital.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        agregarAlHospital.setBorderPainted(false);
        agregarAlHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarAlHospital.setDoubleBuffered(true);
        agregarAlHospital.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        agregarAlHospital.setIconTextGap(8);
        agregarAlHospital.setPreferredSize(new java.awt.Dimension(10, 10));
        agregarAlHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputDepRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNacRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputDniRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNombreRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputSexoRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(agregarAlHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(botonPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputNombreRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSexoRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDniRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNacRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDepRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addComponent(botonPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(agregarAlHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNacRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNacRecepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNacRecepActionPerformed

    private void inputDepRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDepRecepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDepRecepActionPerformed

    private void inputNombreRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreRecepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreRecepActionPerformed

    private void inputSexoRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSexoRecepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSexoRecepActionPerformed

    private void inputDniRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDniRecepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDniRecepActionPerformed

    private void botonPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrincipal1ActionPerformed
        String nombre= inputNombreRecep.getText();
       String sexo = inputSexoRecep.getText();
       String dni = inputDniRecep.getText();
       String nac = inputNacRecep.getText();
       String dto =inputDepRecep.getText();
 
       Recepcionista recep= new Recepcionista();
           recep.setAreaAtencion(dto);
       recep.setNombre(nombre);
       recep.setSexo(sexo);
       recep.setDni(dni);
       recep.setNacionalidad(nac);
   
       
       
       listaRecepcionista.agregar(recep);
       JOptionPane.showMessageDialog(null, "Se ha guardado correctamente");
        
        

        inputNombreRecep.setText("");
        inputSexoRecep.setText("");
        inputDniRecep.setText("");
        inputNacRecep.setText("");
        inputDepRecep.setText("");
        
        
        
        
    }//GEN-LAST:event_botonPrincipal1ActionPerformed

    private void agregarAlHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlHospitalActionPerformed
      int obtenerUltimo = listaHospitales.getTamaño()-1;
      listaHospitales.obtener(obtenerUltimo).setRecepcionista(listaRecepcionista);
      listaRecepcionista= new MiLista();
            }//GEN-LAST:event_agregarAlHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlHospital;
    private javax.swing.JButton botonPrincipal1;
    private javax.swing.JTextField inputDepRecep;
    private javax.swing.JTextField inputDniRecep;
    private javax.swing.JTextField inputNacRecep;
    private javax.swing.JTextField inputNombreRecep;
    private javax.swing.JTextField inputSexoRecep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
