/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Logica.Administracion;
import Logica.Hospital;
import Logica.MiLista;
import Logica.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FormAdmin extends javax.swing.JPanel {
private MiLista<Hospital> listaHospitales;
    private MiLista<Administracion> listaAdmin = new MiLista<>();
    /**
     * Creates new form FormAdmin
     */
    public FormAdmin() {
        initComponents();
        Principal principal = new Principal();
        listaHospitales = principal.obtenerListaHospitales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputSexoAdmin = new javax.swing.JTextField();
        inputDniAdmin = new javax.swing.JTextField();
        inputNacAdmin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputDepAdmin = new javax.swing.JTextField();
        inputNombreAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        agregarAlHospital = new javax.swing.JButton();
        botonPrincipal2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel1.setText("Carga personal administracion");

        jLabel3.setText("Sexo:");

        jLabel4.setText("Departamento:");

        jLabel5.setText("DNI:");

        inputSexoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSexoAdminActionPerformed(evt);
            }
        });

        inputDniAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDniAdminActionPerformed(evt);
            }
        });

        inputNacAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNacAdminActionPerformed(evt);
            }
        });

        jLabel8.setText("Nacionalidad:");

        inputDepAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDepAdminActionPerformed(evt);
            }
        });

        inputNombreAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreAdminActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre completo:");

        agregarAlHospital.setBackground(new java.awt.Color(132, 255, 102));
        agregarAlHospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarAlHospital.setForeground(new java.awt.Color(255, 255, 255));
        agregarAlHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        agregarAlHospital.setText("Agregar al hospital");
        agregarAlHospital.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        agregarAlHospital.setBorderPainted(false);
        agregarAlHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarAlHospital.setDoubleBuffered(true);
        agregarAlHospital.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        agregarAlHospital.setIconTextGap(8);
        agregarAlHospital.setPreferredSize(new java.awt.Dimension(10, 10));
        agregarAlHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlHospitalActionPerformed(evt);
            }
        });

        botonPrincipal2.setBackground(new java.awt.Color(132, 255, 102));
        botonPrincipal2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonPrincipal2.setForeground(new java.awt.Color(255, 255, 255));
        botonPrincipal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-crear-24.png"))); // NOI18N
        botonPrincipal2.setText("Agregar");
        botonPrincipal2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonPrincipal2.setBorderPainted(false);
        botonPrincipal2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPrincipal2.setDoubleBuffered(true);
        botonPrincipal2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPrincipal2.setIconTextGap(8);
        botonPrincipal2.setPreferredSize(new java.awt.Dimension(10, 10));
        botonPrincipal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrincipal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(agregarAlHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputDepAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputNacAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputDniAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputSexoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(botonPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSexoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDniAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNacAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDepAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addComponent(botonPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregarAlHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputSexoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSexoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSexoAdminActionPerformed

    private void inputDniAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDniAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDniAdminActionPerformed

    private void inputNacAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNacAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNacAdminActionPerformed

    private void inputDepAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDepAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDepAdminActionPerformed

    private void inputNombreAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreAdminActionPerformed

    private void agregarAlHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlHospitalActionPerformed
       int obtenerUltimo = listaHospitales.getTamaño() - 1;
       listaHospitales.obtener(obtenerUltimo).setAdministracion(listaAdmin);
    
        listaAdmin = new MiLista();
    
    }//GEN-LAST:event_agregarAlHospitalActionPerformed

    private void botonPrincipal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrincipal2ActionPerformed
        String nombre= inputNombreAdmin.getText();
        String sexo = inputSexoAdmin.getText();
        String dni = inputDniAdmin.getText();
        String nac = inputNacAdmin.getText();
        String dto =inputDepAdmin.getText();
        
        

        Administracion admin= new Administracion();
          admin.setDepartamento(dto);
        admin.setNombre(nombre);
        admin.setSexo(sexo);
        admin.setDni(dni);
        admin.setNacionalidad(nac);
      

        listaAdmin.agregar(admin);
        JOptionPane.showMessageDialog(null, "Se ha guardado correctamente");
        
        
        inputNombreAdmin.setText("");
        inputSexoAdmin.setText("");
        inputDniAdmin.setText("");
        inputNacAdmin.setText("");
        inputDepAdmin.setText("");
        
        
    }//GEN-LAST:event_botonPrincipal2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlHospital;
    private javax.swing.JButton botonPrincipal2;
    private javax.swing.JTextField inputDepAdmin;
    private javax.swing.JTextField inputDniAdmin;
    private javax.swing.JTextField inputNacAdmin;
    private javax.swing.JTextField inputNombreAdmin;
    private javax.swing.JTextField inputSexoAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
